### ISSUE TITLE
Transaction import hangs when transaction may belong to one of a subset of categories

### ISSUE THREAD

**Issue by MusikPolice** [MusikPolice/ofxcat#8]
Ran into an issue while categorizing a transaction that might have belonged to one of two existing categories. Was prompted to choose which of the two, but then something went wrong and I was prompted to choose from the entire list of categories. The application hanged for maybe a minute and then proceeded with the next transaction.

Here's the UI:
```
Found new transaction:
Date: 2018-12-17
Type: DEBIT
Amount: -$300.00
Description: LOAN PMT

Select an existing category for the transaction:
  1: VISA
  2: UTILITIES
  3: Choose another Category
Enter your choice: 1

Select an existing category for transaction:
   1: ALCOHOL
   2: CASH
   3: CELLPHONES
   4: GROCERIES
   5: HAIRCUTS
   6: HEALTH
   7: HOME IMPROVEMENT
   8: INCOME
   9: MORTGAGE
  10: PETS
  11: RESTAURANTS
  12: SHOPPING
  13: UNKNOWN
  14: UTILITIES
  15: VACATION
  16: VISA
  17: New Category
Enter your choice: 16

Categorized transaction as VISA
```
Relevant logs:
```
16:36:02.975 DEBUG c.j.o.d.CategorizedTransactionDao - Attempting to determine if Transaction{type=DEBIT, date=2018-12-17, amount=-300.0, description='LOAN PMT', account=Account{bankId='xxxxx', accountId='yyyyy', accountType='CHECKING', name='Chequing', id=1}, balance=2456.0452} is a duplicate
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - ResultSet contained zero results
16:36:02.975 DEBUG o.b.textio.jline.JLineTextTerminal - ansiColor(3, gray) = [1;37m
16:36:02.975 DEBUG o.b.textio.jline.JLineTextTerminal - ansiColor(3, white) = [1;37m
16:36:02.975 DEBUG o.b.textio.jline.JLineTextTerminal - ansiColor(3, gray) = [1;37m
16:36:02.975 DEBUG o.b.textio.jline.JLineTextTerminal - ansiColor(3, white) = [1;37m
16:36:02.975 DEBUG o.b.textio.jline.JLineTextTerminal - ansiColor(3, gray) = [1;37m
16:36:02.975 DEBUG o.b.textio.jline.JLineTextTerminal - ansiColor(3, white) = [1;37m
16:36:02.975 DEBUG o.b.textio.jline.JLineTextTerminal - ansiColor(3, gray) = [1;37m
16:36:02.975 DEBUG o.b.textio.jline.JLineTextTerminal - ansiColor(3, white) = [1;37m
16:36:02.975 DEBUG c.j.o.d.DescriptionCategoryDao - Attempting to select all DescriptionCategory objects
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 1
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 2
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 3
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 4
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 5
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 5
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 6
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 2
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 7
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 8
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 5
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 2
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 9
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 10
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 11
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 12
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 13
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 1
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 7
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 1
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 14
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 15
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 1
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 16
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 12
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 25 results
16:36:02.975 DEBUG c.j.o.s.TransactionCategoryService - Fuzzy category matches for transaction description "LOAN PMT":
16:36:02.975 DEBUG c.j.o.d.DescriptionCategoryDao - Attempting to select all DescriptionCategory objects
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 1
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 2
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 3
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 4
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 5
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 5
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 6
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 2
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 7
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 8
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 5
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 2
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 9
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 10
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 11
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 12
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 13
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 1
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 7
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 1
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 14
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 15
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 1
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 16
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 12
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:02.975 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 25 results
16:36:02.975 DEBUG c.j.o.s.TransactionCategoryService - LOAN PMT: 100
16:36:02.975 DEBUG c.j.o.s.TransactionCategoryService - UTILITY BILL PMT UTILITIES: 86
16:36:02.975 DEBUG c.j.o.s.TransactionCategoryService - HYDRO BILL PMT KIT-WIL HYDRO: 86
16:36:17.815 DEBUG c.j.o.d.DescriptionCategoryDao - Attempting to select DescriptionCategory with description LOAN PMT and Category Category{id=4, name='VISA'}
16:36:17.815 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 4
16:36:17.815 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:17.815 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:17.815 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to select all Category objects
16:36:17.815 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 16 results
16:36:29.353 DEBUG c.j.o.d.DescriptionCategoryDao - Attempting to select DescriptionCategory with description LOAN PMT and Category Category{id=null, name='VISA'}
16:36:29.353 DEBUG c.j.ofxcat.datastore.CategoryDao - Attempting to query Category with id 4
16:36:29.353 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:29.353 DEBUG c.j.o.d.utils.ResultSetDeserializer - Found 1 results
16:36:29.353 DEBUG o.b.textio.jline.JLineTextTerminal - ansiColor(3, gray) = [1;37m
16:36:29.353 DEBUG o.b.textio.jline.JLineTextTerminal - ansiColor(3, white) = [1;37m
16:36:29.353 INFO  c.j.o.s.TransactionImportService - Categorized Transaction Transaction{type=DEBIT, date=2018-12-17, amount=-300.0, description='LOAN PMT', account=Account{bankId='xxxxx', accountId='yyyyy', accountType='CHECKING', name='Chequing', id=1}, balance=2456.0452} as Category{id=4, name='VISA'}
16:36:29.353 DEBUG c.j.o.d.CategorizedTransactionDao - Attempting to insert CategorizedTransaction CategorizedTransaction{id=null, category=Category{id=4, name='VISA'}}
```

**Comment by MusikPolice** [comment]
Got a crash that appears to be related:
```
Found new transaction:
Date: 2018-12-24
Type: DEBIT
Amount: -$300.00
Description: LOAN PMT

Select an existing category for the transaction:
  1: VISA
  2: UTILITIES
  3: LINE OF CREDIT
  4: Choose another Category
Enter your choice: 3

Select an existing category for transaction:
   1: ALCOHOL
   2: AUTO INSURANCE
   3: CASH
   4: CELLPHONES
   5: ENTERTAINMENT
   6: GAS
   7: GROCERIES
   8: HAIRCUTS
   9: HEALTH
  10: HOME IMPROVEMENT
  11: INCOME
  12: LINE OF CREDIT
  13: MORTGAGE
  14: PETS
  15: RESTAURANTS
  16: SHOPPING
  17: UNKNOWN
  18: UTILITIES
  19: VACATION
  20: VISA
  21: New Category
Enter your choice: 12



Categorized transaction as VISA

Found new transaction:
Date: 2018-12-24
Type: DEBIT
Amount: -$15.59
Description: DOLLARAMA # 257
Exception in thread "main" java.lang.IllegalStateException: Duplicate key LOAN PMT (attempted merging values Category{id=4, name='VISA'} and Category{id=19, name='LINE OF CREDIT'})
        at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
        at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at ca.jonathanfritz.ofxcat.service.TransactionCategoryService.getCategoryExact(TransactionCategoryService.java:52)
        at ca.jonathanfritz.ofxcat.cli.CLI.categorizeTransaction(CLI.java:112)
        at ca.jonathanfritz.ofxcat.service.TransactionImportService.lambda$categorizeTransactions$5(TransactionImportService.java:115)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at ca.jonathanfritz.ofxcat.service.TransactionImportService.categorizeTransactions(TransactionImportService.java:108)
        at ca.jonathanfritz.ofxcat.service.TransactionImportService.importTransactions(TransactionImportService.java:71)
        at ca.jonathanfritz.ofxcat.OfxCat.importTransactions(OfxCat.java:61)
        at ca.jonathanfritz.ofxcat.OfxCat.main(OfxCat.java:106)
```

**Comment by MusikPolice** [comment]
The crash was caused by one transaction description, in this case "LOAN PMT", being linked to two different categories:
![image](https://user-images.githubusercontent.com/1799952/100554673-327b6c80-3264-11eb-8412-4a20220d3307.png)

When this happens, code in `TransactionCategoryService.getCategoryExact(...)` that assumes that each transaction description is linked to exactly one category blows up while trying to assemble a map of with descriptions as keys. The map must have non-duplicate keys, so it breaks.

**Comment by MusikPolice** [comment]
Fixed crash that occurred when a description string is linked to two or more categories in b087451
